### ISSUE TITLE
Bridge responseTime tracking adds 90 seconds instead of 15 seconds

### ISSUE THREAD

**Issue by littleskunk** [Storj/complex#48]
### Expected Behavior

Timeout is 15 seconds https://github.com/Storj/core/blob/1994ba3f8d2acd5123e8e1ab557f65b2d656336d/lib/constants.js#L16

On timeout the bridge should add 15 seconds to the responseTime moving average

### Actual Behavior

The bridge is adding 90 seconds. That is not correct. The farmer is not able to send any response that late. He will calculate with a timeframe of only 15 seconds and drop everything higher.

I tracked my responseTime over a longer periode. This is the lowest increase I could find. 170ms difference. Quick math with the moving average calculation (https://github.com/Storj/service-storage-models/blob/78b3fbd43969c565f98956dd9fff4d37a99f8ecc/lib/models/contact.js#L135) and the result is a timeout of ~90 seconds. 
```
"lastTimeout":"2017-04-15T09:41:55.357Z","responseTime":9189.118950921893
"lastTimeout":"2017-04-15T10:45:39.573Z","responseTime":9359.549721866048
```

At the end it is this timeout: https://github.com/Storj/complex/blob/3facabb8a5ce5029da99c4e5842d6c10cb4d59d2/lib/landlord.js#L52

Looks like _opts.requestTimeout is empty: https://github.com/Storj/complex/blob/3facabb8a5ce5029da99c4e5842d6c10cb4d59d2/lib/landlord.js#L47

**Comment by braydonf** [comment]
`responseTime` tracks responses, if there was a response in 15 seconds, this would make sense. However when there isn't a response, it's decreasing the `responseTime` so that the value will reflect timeout results when sorting only by `responseTime`, even though there wasn't a response.

Regardless, there are several timeout values and we should make sure that they at least are matching, 15 seconds seems somewhat low, 20 seconds I think is typically the default.

**Comment by littleskunk** [comment]
Close as user error?

Increasing the core timeout is not needed from the farmer side. I get everything in time.
The bridge should hopefully don't count error responses as timeouts. I had a periode of 2 days without any timeouts. I think both timeouts are valid and don't need to be changed. At least not for this issue.

**Comment by braydonf** [comment]
We've decreased the timeout to 30 seconds, for another purpose.
