### ISSUE TITLE
Unable getStorageOffer job times out

### ISSUE THREAD

**Issue by abrkn** [Storj/complex#74]
When trying to upload a file from storj cli using my own bridge and complex, the complex logs shows (repeatedly):

```
{"level":"info","message":"queueing job, method: getStorageOffer, id: c21ca324-c9c8-4c34-9c55-915de147749c, data_hash: 7e997d4d0c5207d563081040f33c20fac300d48e, node_id: undefined","timestamp":"2017-08-13T12:55:28.456Z"}
```

The storj client hangs at "Preparing file..."

Ideas?

**Comment by littleskunk** [comment]
It will hopefully be solved with https://github.com/Storj/sips/blob/master/sip-0006.md

**Comment by braydonf** [comment]
This likely has to due with the fact that the "trusted key" for farmers is configured to not accept arbitrary contracts, any new bridge (complex) would need to have farmers add their trusted key. This causes some friction when starting new bridges, as well as the several manual processes that would be necessary, such as sending payments to farmers.

From the farmer (storjshare) side, config options to accept contracts and data from multiple bridges is in the works, see https://github.com/Storj/integration/pull/5/files Next we can streamline the process for new bridges to join with something such as https://github.com/Storj/sips/pull/20/files and then work on automating farmer payouts.

Many of these problems are detailed with potential solutions in:
- https://github.com/Storj/sips/pull/20
- https://github.com/Storj/sips/pull/34

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
